sudo: required
services:
  - docker

before_install:
  - docker build -t ramadanmostafa/docker-react -f Dockerfile.dev .

script:
  - docker run ramadanmostafa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-React-env"
  bucket_name: "elasticbeanstalk-us-west-2-306477501214548"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
