sudo: required
services:
  - docker

before_install:
  - docker build -t ramadanmostafa/docker-react -f Dockerfile.dev .

script:
  - docker run ramadanmostafa/docker-react npm run test -- --coverage
